version: 2
jobs:
  build:
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
      - checkout

      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH

      - type: shell
        command: |
          # Need to add this into circleci global variables
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name "Ranjit Redekar"

      - type: shell
        command: |
          # mkdir ../$CIRCLE_BRANCH
          # jekyll build --destination ../$CIRCLE_BRANCH
          jekyll build
          pwd

      # Deploy to Github pages
      - type: shell
        command: |
          pwd
          cd _site
          ls
          #aws s3 sync --delete . s3://sunbird-docs-qa/web/pr/$CIRCLE_PR_NUMBER
          prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird.org-web/issues/$CIRCLE_PR_NUMBER)
          username=$(echo "${prdata}" | jq '.user.login')
          contributor=${username//\"/}
          updatedfiles=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird.org-web/pulls/$CIRCLE_PR_NUMBER/files)
          updatedfileslist=''
          updatedsectionslist=''
          for row in $(echo "${updatedfiles}" | jq -r '.[] | @base64')
          do  
          _jq() 
          {
            echo ${row} | base64 --decode | jq -r ${1}
          }
          file=$(_jq '.filename')
          echo $file

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
