version: 2
jobs:
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
            
      # Run Build command
      - type: shell
        name: Build & Deploy
        command: |
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete . s3://sunbird-docs-qa/web-staging/
  prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      #Checkout
      - checkout
          
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
      #Add User
      - type: shell
        name: Configure git
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
      
      # Pull Code from staging site
      - type: shell
        name: Download code from staging
        command: |
          cd ..
          rm -rf downloads
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://sunbird-docs-qa/web-staging/ .
           
      # Deploy to Gitpages
      - type: shell
        name: Deploy code to gh-pages repo
        command: |
          cd ..
          rm -rf deploy
          mkdir deploy
          cd deploy
          git clone -b gh-pages git@github.com:project-sunbird/sunbird.org-web.git cloned-repo
          cd cloned-repo
          cp -R .git/ ../
          rm -rf *
          cd ..
          cp -R ../downloads/* cloned-repo/
          cp -R .git/ cloned-repo/
          cd cloned-repo/
          git add -A
          git commit -m "Deploy - $CIRCLE_BUILD"
          git push origin gh-pages
          
workflows:
  version: 2
  web-build-deploy:
    jobs:
      - staging
      - hold:
          type: approval
          requires:
              - staging
      - prod:
          requires:
              - hold
