version: 2
jobs:
  build:
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
      - checkout

      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH

      - type: shell
        command: |
          # Need to add this into circleci global variables
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name "Ranjit Redekar"

      - type: shell
        command: |
          mkdir ../$CIRCLE_BRANCH
          jekyll build --destination ../$CIRCLE_BRANCH

      # Deploy to Github pages
      - type: shell
        command: |
          cd ..
          git clone -b gh-pages "$CIRCLE_REPOSITORY_URL" appRepo
          cd appRepo
          rm -R ./*
          mv -f ../$CIRCLE_BRANCH/ .
          git add -A
          git commit -m "$CIRCLE_BRANCH - $CIRCLE_BUILD_NUM"
          git push origin gh-pages
