version: 2
jobs:
  pr:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      # Checkout
      - checkout
        
      # Run Build command & deploy to PR site
      - type: shell
        name: PR - Build & Deploy
        command: |
          if [[ -z "$CIRCLE_PR_NUMBER" ]]
          then
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete . s3://sunbird-docs-qa/web-pr/$CIRCLE_PR_NUMBER
          fi
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      # Checkout
      - checkout
       
      # Run Build command & Deploy to Staging site
      - type: shell
        name: Commit - Build & Deploy
        command: |
          if [[! -z "$CIRCLE_PR_NUMBER" ]]
          then
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete . s3://sunbird-docs-qa/web-staging/
          fi
  prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      # Checkout
      - checkout
      
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
            
      # Configure Git
      - type: shell
        name: Configure git
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
      
      # Download code from staging
      - type: shell
        name: Download code from staging
        command: |
          cd ..
          rm -rf downloads
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://sunbird-docs-qa/web-staging/ .
           
      # Deploy to Gitpages
      - type: shell
        name: Deploy code to gh-pages repo
        command: |
          cd ..
          rm -rf deploy
          mkdir deploy
          cd deploy
          git clone -b gh-pages git@github.com:project-sunbird/sunbird.org-web.git cloned-repo
          cd cloned-repo
          cp -R .git/ ../
          rm -rf *
          cd ..
          cp -R ../downloads/* cloned-repo/
          cp -R .git/ cloned-repo/
          cd cloned-repo/
          git add -A
          git commit -m "Deploy Web - $CIRCLE_BUILD_NUM"
          git push origin gh-pages
          
workflows:
  version: 2
  web-build-deploy:
    jobs:
      - pr
      - staging
          filters:
            branches:
              only: /^master.*/
      - hold:
          type: approval
          requires:
              - staging
      - prod:
          requires:
              - hold
