version: 2
jobs:
  pr:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      # Checkout
      - checkout
        
      # Run Build command & deploy to PR site
      - type: shell
        name: PR - Build & Deploy
        command: |
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete . s3://sunbird-docs-qa/web-pr/$CIRCLE_PR_NUMBER
          
      # Comment on PR
      - type: shell
        name: PR - Add comment on PR with URL details
        command: |
         prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird.org-web/issues/$CIRCLE_PR_NUMBER) 
         username=$(echo "${prdata}" | jq '.user.login')
         contributor=${username//\"/}
         curl \
          -X POST \
          -u $GITHUB_USER_TOKEN:x-oauth-basic \
          -d '{"body": "Hello @'"$contributor"',<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - <a href="http://'"$CIRCLE_PR_NUMBER"'.www-qa.sunbird.org" target="_blank">http://'"$CIRCLE_PR_NUMBER"'.www-qa.sunbird.org</a> ."}' \
          https://api.github.com/repos/project-sunbird/sunbird.org-web/issues/$CIRCLE_PR_NUMBER/comments
          
  staging:
    working_directory: /project/workplace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      # Checkout
      - checkout
       
      # Run Build command & Deploy to Staging site
      - type: shell
        name: Commit - Build & Deploy
        command: |
          echo "buildNo: $CIRCLE_BUILD_NUM" >> _config.yml
          bundle install
          bundle exec jekyll build
          cd _site
          aws s3 sync --delete . s3://sunbird-docs-qa/web-staging/
  prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
    
      # Checkout
      - checkout
      
      # Add SSH Key   
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH_FINGERPRINT
            
      # Configure Git
      - type: shell
        name: Configure git
        command: |
          git config --global user.email $GITHUB_USER_EMAIL
          git config --global user.name $GITHUB_USER_NAME
      
      # Download code from staging
      - type: shell
        name: Download code from staging
        command: |
          cd ..
          rm -rf downloads
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://sunbird-docs-qa/web-staging/ .
           
      # Deploy to Gitpages
      - type: shell
        name: Deploy code to gh-pages repo
        command: |
          cd ..
          rm -rf deploy
          mkdir deploy
          cd deploy
          git clone -b gh-pages $CIRCLE_REPOSITORY_URL cloned-repo
          cd cloned-repo
          cp -R .git/ ../
          rm -rf *
          cd ..
          cp -R ../downloads/* cloned-repo/
          cp -R .git/ cloned-repo/
          cd cloned-repo/
          git add -A
          git commit -m "Deploy Web - Build No. $CIRCLE_BUILD_NUM"
          git push origin gh-pages
          
workflows:
  version: 2
  web-build-deploy:
    jobs:
      - pr:
          filters:
            branches:
              ignore:
                - master
                - gh-pages
      - staging:
          filters:
            branches:
              only:
                - master
      - hold:
          type: approval
          requires:
              - staging
          filters:
            branches:
              only:
                - master
      - prod:
          requires:
              - hold
          filters:
            branches:
              only:
                - master
