version: 2
jobs:
  build:
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:
      - checkout

      # Add SSH Key
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH

      - type: shell
        command: |
          # Need to add this into circleci global variables
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name "Ranjit Redekar"

      - type: shell
        command: |
          # mkdir ../$CIRCLE_BRANCH
          # jekyll build --destination ../$CIRCLE_BRANCH
          jekyll build
          pwd

      # Deploy to Amazon S3
      - type: shell
        command: |
          pwd
          cd _site
          ls
          aws s3 sync --delete . s3://sunbird-docs-qa/web/pr/$CIRCLE_PR_NUMBER
          prdata=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird.org-web/issues/$CIRCLE_PR_NUMBER)
          username=$(echo "${prdata}" | jq '.user.login')
          contributor=${username//\"/}
          updatedfiles=$(curl -X GET -u $GITHUB_USER_TOKEN:x-oauth-basic https://api.github.com/repos/project-sunbird/sunbird.org-web/pulls/$CIRCLE_PR_NUMBER/files)
          updatedfileslist=''
          updatedsectionslist=''
          for row in $(echo "${updatedfiles}" | jq -r '.[] | @base64')
          do
           _jq()
           {
             echo ${row} | base64 --decode | jq -r ${1}
           }
           file=$(_jq '.filename')
           echo $file
           if [[ "$file" == pages/* ]] && [[ "$file" == *.md ]]
           then
             filedocs=${file//\.md/}
             filedocs=${filedocs//index/}
             filedocs=${filedocs//.html/}
             filedocs=${filedocs//pages\//}
              url='- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/web/pr/'$CIRCLE_PR_NUMBER'/'$filedocs' <br /> '
             updatedfileslist=$updatedfileslist$url
             echo $url
           fi
           if [[ "$file" == apis/* ]]
           then
             fileremove=${file##*/}
             echo $fileremove
             fileapi=${file//$fileremove/}
             url='- http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/web/pr/'$CIRCLE_PR_NUMBER'/'$fileapi' <br /> '
             updatedfileslist=$updatedfileslist$url
             echo $url
           fi
           if [[ "$file" == _includes/* ]]
           then
             sections=${file//.html/}
             sections=${sections//_includes\//}
             url='- '$sections' <br /> '
             updatedsectionslist=$updatedsectionslist$url
           fi
          done
          curl \
            -X POST \
            -u $GITHUB_USER_TOKEN:x-oauth-basic \
            -d '{"body": "Hello @'"$contributor"',<br/><br/> _This is a auto-generated response._ <br/> Click the URL for review pull request - http://sunbird-docs-qa.s3-website.ap-south-1.amazonaws.com/pr/'"$CIRCLE_PR_NUMBER"'. <br/><br/> **Modified pages are -** <br />'"$updatedfileslist"' <br/> **Modified sections are -** <br />'"$updatedsectionslist"' "}' \
            https://api.github.com/repos/project-sunbird/sunbird.org-web/web/issues/$CIRCLE_PR_NUMBER/comments

  prod:
    working_directory: /project/workspace/
    docker:
      - image: lakhanmandloi/sunbird-ubuntu-fuller
    steps:

      #Checkout
      - checkout

      # Add SSH Key
      - add_ssh_keys:
          fingerprints:
            - $GITHUB_SSH

      - type: shell
        command: |
          # Need to add this into circleci global variables
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name "Ranjit Redekar"

      # Pull Code from staging site
      - type: shell
        command: |
          cd ..
          mkdir downloads
          cd downloads
          aws s3 sync --delete s3://sunbird-docs-qa/web/$CIRCLE_TAG .
          ls
      # Deploy to Gitpages
      - type: shell
        command: |
          # cd ..
          # mkdir deploy
          # cd deploy
          # git clone git@github.com:project-sunbird/project-sunbird.github.io.git
          # cd project-sunbird.github.io
          # git checkout master
          # cp -R .git/ ../
          # rm -rf *
          # cd ..
          # cp -R ../downloads/* project-sunbird.github.io/
          # cp -R .git/ project-sunbird.github.io/
          # cd project-sunbird.github.io/
          # git add -A
          # git commit -m "$CIRCLE_TAG"
          # git push origin master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
              - build
      - prod:
          requires:
              - hold